//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solti.Utils.Primitives.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solti.Utils.Primitives.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispose can not be called directly..
        /// </summary>
        internal static string ARBITRARY_RELEASE {
            get {
                return ResourceManager.GetString("ARBITRARY_RELEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The child already assigned to a parent..
        /// </summary>
        internal static string BELONGING_ITEM {
            get {
                return ResourceManager.GetString("BELONGING_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent cannot be set directly..
        /// </summary>
        internal static string CANT_SET_PARENT {
            get {
                return ResourceManager.GetString("CANT_SET_PARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given interface ({0}) is not supported..
        /// </summary>
        internal static string INTERFACE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("INTERFACE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of children exceeded the limit ({0})..
        /// </summary>
        internal static string TOO_MANY_CHILDREN {
            get {
                return ResourceManager.GetString("TOO_MANY_CHILDREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value has already been set..
        /// </summary>
        internal static string VALUE_ALREADY_SET {
            get {
                return ResourceManager.GetString("VALUE_ALREADY_SET", resourceCulture);
            }
        }
    }
}
